version: '3'

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
    - '3000:3000'
    volumes: 
    - app/node_modules #membuat app/node_modules di container tidak di map
    - .:/app #membuat aplikasi hot reload
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - app/node_modules
      - .:/app
    command: ["npm","run","test"]